#!/usr/bin/env bash
if [ $# != 2 ]; then
echo
echo "Usage:       $0 [tftp_dir] [version]"
echo
echo "for example: $0 `pwd` 2018.2"
echo
exit 1;
fi

tftp_dir=$1
version=$2

echo 
echo Make sure you have already put [petalinux-v$version-final-installer.run] in the [$tftp_dir]
echo Start to build petalinux tools docker image
echo

cd $tftp_dir
python3 -m http.server &
server_pid=$!
echo 
echo PID ${server_pid}
echo http.server starting...
echo

#installer_ip=`ifconfig docker0 | grep 'inet\s' | awk '{print $2}' | cut -c 6-`
#echo $installer_ip
cd $version
docker build -t petalinux:$2 .

kill $server_pid

echo "---------------"
echo "finish building"
echo "---------------"
