#!/usr/bin/env bash
if [ $# != 2 ]; then
echo
echo "Usage:       $0 [tftp_dir] [version]"
echo
echo "for example: $0 `pwd` 2018.2"
echo
exit 1;
fi

docker_context=`pwd`
tftp_dir=$1
version=$2

if [ ! -d "petalinux-v${version}-final-installer.run" ]; then
echo 
echo Make sure you have already put [petalinux-v${version}-final-installer.run] in the [${tftp_dir}]
fi

echo Start to build petalinux tools docker image
echo

cd ${tftp_dir}
python3 -m http.server &
server_pid=$!
echo 
echo PID ${server_pid}
echo http.server starting...
echo

cd ${docker_context}
timestamp=`date +"%Y-%m-%d-%H-%M-%S"`
docker build -t sonnyhcl/petalinux:$timestamp .
docker tag sonnyhcl/petalinux:$timestamp sonnyhcl/petalinux:latest

kill ${server_pid}

echo "---------------"
echo "finish building"
echo "---------------"
docker images | grep petalinux
